### ISSUE TITLE
Object has been destroyed

### ISSUE THREAD

**Issue by linonetwo** [i18next/i18next-node-fs-backend#242]
After closing window, and click the tray icon to recreate window, I get following error:

```
Uncaught Exception:
Error: Object has been destroyed
    at BrowserWindow.<anonymous> (/xxx/node_modules/i18next-electron-fs-backend/lib/index.js:1:2234)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

In https://github.com/reZach/secure-electron-template

**Comment by linonetwo** [comment]
Oh, it is electron fs backend, I mistook.
